# -*- coding: utf-8 -*-
"""visualize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qPilxM1Q1TNwXof-BcRBXneMSgw8aIze
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.datasets import fashion_mnist

# Load the dataset
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

# Normalizing images
x_train = x_train.reshape(x_train.shape[0], -1) / 255.0
x_test = x_test.reshape(x_test.shape[0], -1) / 255.0

# One-hot encoding the labels
def one_hot_encode(y, num_classes=10):
    return np.eye(num_classes)[y]

y_train_ohe = one_hot_encode(y_train)
y_test_ohe = one_hot_encode(y_test)

# Find the first occurrence of each class manually
# Dictionary to store first occurrences of each label
first_indices = {}
for i, label in enumerate(y_train):
      # Store the first occurrence
    if label not in first_indices:
        first_indices[label] = i
      # Stop when all 10 classes are found
    if len(first_indices) == 10:
        break

# Display one sample per class
fig, axes = plt.subplots(4, 3, figsize=(9, 12))
labels = ["T-shirt", "Trouser", "Pullover", "Dress", "Coat",
          "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]

for i in range(10):
    ax = axes[i // 3, i % 3]
    idx = first_indices[i]
    ax.imshow(x_train[idx].reshape(28, 28), cmap='gray')
    ax.set_title(labels[i])
    ax.axis('off')

for j in range(10, 12):
    fig.delaxes(axes[j // 3, j % 3])

plt.tight_layout()
plt.show()